(*) rook-ceph.sh: wait for nfs pods before running ceph nfs commands
This may (?) be a fix for this error which has occasionally been seen
when running `rook-ceph.sh`.:

    Error EINVAL: Traceback (most recent call last):
      File "/usr/share/ceph/mgr/mgr_module.py", line 1448, in _handle_command
	return CLICommand.COMMANDS[cmd['prefix']].call(self, cmd, inbuf)
      File "/usr/share/ceph/mgr/mgr_module.py", line 414, in call
	return self.func(mgr, **kwargs)
      File "/usr/share/ceph/mgr/nfs/module.py", line 65, in _cmd_nfs_export_rm
	return self.export_mgr.delete_export(cluster_id=cluster_id, pseudo_path=pseudo_path)
      File "/usr/share/ceph/mgr/nfs/export.py", line 60, in cluster_check
	clusters = known_cluster_ids(export.mgr)
      File "/usr/share/ceph/mgr/nfs/export.py", line 45, in known_cluster_ids
	clusters = set(available_clusters(mgr))
      File "/usr/share/ceph/mgr/nfs/utils.py", line 39, in available_clusters
	orchestrator.raise_if_exception(completion)
      File "/usr/share/ceph/mgr/orchestrator/_interface.py", line 228, in raise_if_exception
	raise e
    kubernetes.client.rest.ApiException: ({'type': 'ERROR', 'object': {'api_version': 'v1',
     'kind': 'Status',
     'metadata': {'annotations': None,
		  'cluster_name': None,
		  'creation_timestamp': None,
		  'deletion_grace_period_seconds': None,
		  'deletion_timestamp': None,
		  'finalizers': None,
		  'generate_name': None,
		  'generation': None,
		  'initializers': None,
		  'labels': None,
		  'managed_fields': None,
		  'name': None,
		  'namespace': None,
		  'owner_references': None,
		  'resource_version': None,
		  'self_link': None,
		  'uid': None},
     'spec': None,
     'status': {'conditions': None,
		'container_statuses': None,
		'host_ip': None,
		'init_container_statuses': None,
		'message': None,
		'nominated_node_name': None,
		'phase': None,
		'pod_ip': None,
		'qos_class': None,
		'reason': None,
		'start_time': None}}, 'raw_object': {'kind': 'Status', 'apiVersion': 'v1', 'metadata': {}, 'status': 'Failure', 'message': 'too old resource version: 300635216 (300775073)', 'reason': 'Expired', 'code': 410}})
    Reason: None